// Trilingual Vocabulary — 500 Core Concepts
// English (EN) · Spanish (ES) · Dutch (NL)
// Organized by frequency/usefulness. Each entry includes example sentences in ES and NL.

const VOCABULARY = [
  // ── 1–50: Essential Function Words ──────────────────────────────
  { id: 1, en: "and", es: "y", nl: "en", type: "conjunction", ex: { es: "Tengo un perro y un gato.", nl: "Ik heb een hond en een kat." } },
  { id: 2, en: "the", es: "el / la", nl: "de / het", type: "article", ex: { es: "El libro está en la mesa.", nl: "Het boek ligt op de tafel." } },
  { id: 3, en: "is", es: "es / está", nl: "is", type: "verb", ex: { es: "Ella es doctora.", nl: "Zij is dokter." } },
  { id: 4, en: "of, from", es: "de", nl: "van", type: "preposition", ex: { es: "Es la casa de mi madre.", nl: "Het is het huis van mijn moeder." } },
  { id: 5, en: "in, on", es: "en", nl: "in, op", type: "preposition", ex: { es: "Vivo en Madrid.", nl: "Ik woon in Amsterdam." } },
  { id: 6, en: "to, at", es: "a", nl: "naar, aan", type: "preposition", ex: { es: "Voy a la tienda.", nl: "Ik ga naar de winkel." } },
  { id: 7, en: "that, which", es: "que", nl: "dat, die", type: "conjunction", ex: { es: "Creo que tienes razón.", nl: "Ik denk dat je gelijk hebt." } },
  { id: 8, en: "it", es: "lo / ello", nl: "het", type: "pronoun", ex: { es: "Lo veo todos los días.", nl: "Ik zie het elke dag." } },
  { id: 9, en: "not", es: "no", nl: "niet", type: "adverb", ex: { es: "No entiendo la pregunta.", nl: "Ik begrijp de vraag niet." } },
  { id: 10, en: "with", es: "con", nl: "met", type: "preposition", ex: { es: "Vengo con mi amigo.", nl: "Ik kom met mijn vriend." } },
  { id: 11, en: "for", es: "para / por", nl: "voor", type: "preposition", ex: { es: "Esto es para ti.", nl: "Dit is voor jou." } },
  { id: 12, en: "but", es: "pero", nl: "maar", type: "conjunction", ex: { es: "Es difícil, pero posible.", nl: "Het is moeilijk, maar mogelijk." } },
  { id: 13, en: "or", es: "o", nl: "of", type: "conjunction", ex: { es: "¿Quieres café o té?", nl: "Wil je koffie of thee?" } },
  { id: 14, en: "I", es: "yo", nl: "ik", type: "pronoun", ex: { es: "Yo soy estudiante.", nl: "Ik ben student." } },
  { id: 15, en: "you (informal)", es: "tú", nl: "jij / je", type: "pronoun", ex: { es: "Tú eres mi amigo.", nl: "Jij bent mijn vriend." } },
  { id: 16, en: "he", es: "él", nl: "hij", type: "pronoun", ex: { es: "Él trabaja en un banco.", nl: "Hij werkt bij een bank." } },
  { id: 17, en: "she", es: "ella", nl: "zij / ze", type: "pronoun", ex: { es: "Ella habla tres idiomas.", nl: "Zij spreekt drie talen." } },
  { id: 18, en: "we", es: "nosotros", nl: "wij / we", type: "pronoun", ex: { es: "Nosotros vivimos aquí.", nl: "Wij wonen hier." } },
  { id: 19, en: "they", es: "ellos / ellas", nl: "zij / ze", type: "pronoun", ex: { es: "Ellos viven en Barcelona.", nl: "Zij wonen in Rotterdam." } },
  { id: 20, en: "this", es: "este / esta / esto", nl: "dit / deze", type: "pronoun", ex: { es: "Este libro es mío.", nl: "Dit boek is van mij." } },
  { id: 21, en: "that", es: "ese / esa / eso", nl: "dat / die", type: "pronoun", ex: { es: "Ese coche es rápido.", nl: "Die auto is snel." } },
  { id: 22, en: "yes", es: "sí", nl: "ja", type: "adverb", ex: { es: "Sí, estoy de acuerdo.", nl: "Ja, ik ben het ermee eens." } },
  { id: 23, en: "no", es: "no", nl: "nee", type: "adverb", ex: { es: "No, gracias.", nl: "Nee, dank je." } },
  { id: 24, en: "also, too", es: "también", nl: "ook", type: "adverb", ex: { es: "Yo también quiero ir.", nl: "Ik wil ook gaan." } },
  { id: 25, en: "very", es: "muy", nl: "erg / zeer", type: "adverb", ex: { es: "La comida está muy buena.", nl: "Het eten is erg lekker." } },
  { id: 26, en: "already", es: "ya", nl: "al", type: "adverb", ex: { es: "Ya terminé mi tarea.", nl: "Ik heb mijn huiswerk al af." } },
  { id: 27, en: "more", es: "más", nl: "meer", type: "adverb", ex: { es: "Quiero más agua.", nl: "Ik wil meer water." } },
  { id: 28, en: "because", es: "porque", nl: "omdat", type: "conjunction", ex: { es: "Estudio porque quiero aprender.", nl: "Ik studeer omdat ik wil leren." } },
  { id: 29, en: "when", es: "cuando", nl: "wanneer / als", type: "conjunction", ex: { es: "Llámame cuando llegues.", nl: "Bel me wanneer je aankomt." } },
  { id: 30, en: "where", es: "donde", nl: "waar", type: "adverb", ex: { es: "¿Dónde vives?", nl: "Waar woon je?" } },
  { id: 31, en: "how", es: "cómo", nl: "hoe", type: "adverb", ex: { es: "¿Cómo estás?", nl: "Hoe gaat het?" } },
  { id: 32, en: "what", es: "qué", nl: "wat", type: "pronoun", ex: { es: "¿Qué quieres comer?", nl: "Wat wil je eten?" } },
  { id: 33, en: "who", es: "quién", nl: "wie", type: "pronoun", ex: { es: "¿Quién es esa persona?", nl: "Wie is die persoon?" } },
  { id: 34, en: "without", es: "sin", nl: "zonder", type: "preposition", ex: { es: "No puedo vivir sin ti.", nl: "Ik kan niet leven zonder jou." } },
  { id: 35, en: "between", es: "entre", nl: "tussen", type: "preposition", ex: { es: "Está entre la mesa y la silla.", nl: "Het is tussen de tafel en de stoel." } },
  { id: 36, en: "about, over", es: "sobre", nl: "over", type: "preposition", ex: { es: "El libro está sobre la mesa.", nl: "Het boek gaat over de geschiedenis." } },
  { id: 37, en: "until", es: "hasta", nl: "tot", type: "preposition", ex: { es: "Trabajo hasta las cinco.", nl: "Ik werk tot vijf uur." } },
  { id: 38, en: "since, from", es: "desde", nl: "sinds, vanaf", type: "preposition", ex: { es: "Vivo aquí desde hace dos años.", nl: "Ik woon hier sinds twee jaar." } },
  { id: 39, en: "during", es: "durante", nl: "tijdens", type: "preposition", ex: { es: "Llovió durante la noche.", nl: "Het regende tijdens de nacht." } },
  { id: 40, en: "against", es: "contra", nl: "tegen", type: "preposition", ex: { es: "Luchamos contra el tiempo.", nl: "We vechten tegen de tijd." } },
  { id: 41, en: "before", es: "antes", nl: "voor / eerder", type: "adverb", ex: { es: "Llegué antes que tú.", nl: "Ik was er eerder dan jij." } },
  { id: 42, en: "after", es: "después", nl: "na / daarna", type: "adverb", ex: { es: "Después de comer, dormimos.", nl: "Na het eten sliepen we." } },
  { id: 43, en: "always", es: "siempre", nl: "altijd", type: "adverb", ex: { es: "Siempre llega tarde.", nl: "Hij komt altijd te laat." } },
  { id: 44, en: "never", es: "nunca", nl: "nooit", type: "adverb", ex: { es: "Nunca he estado en Japón.", nl: "Ik ben nooit in Japan geweest." } },
  { id: 45, en: "here", es: "aquí", nl: "hier", type: "adverb", ex: { es: "Ven aquí.", nl: "Kom hier." } },
  { id: 46, en: "there", es: "allí / ahí", nl: "daar", type: "adverb", ex: { es: "Espérame allí.", nl: "Wacht daar op mij." } },
  { id: 47, en: "now", es: "ahora", nl: "nu", type: "adverb", ex: { es: "Hazlo ahora.", nl: "Doe het nu." } },
  { id: 48, en: "then", es: "entonces", nl: "dan / toen", type: "adverb", ex: { es: "Entonces, ¿qué hacemos?", nl: "Wat doen we dan?" } },
  { id: 49, en: "well", es: "bien", nl: "goed", type: "adverb", ex: { es: "Todo está bien.", nl: "Alles gaat goed." } },
  { id: 50, en: "much, a lot", es: "mucho", nl: "veel", type: "adverb", ex: { es: "Te quiero mucho.", nl: "Ik hou veel van je." } },

  // ── 51–150: Common Verbs ────────────────────────────────────────
  { id: 51, en: "to be (essence)", es: "ser", nl: "zijn", type: "verb", ex: { es: "Soy profesor.", nl: "Ik ben leraar." } },
  { id: 52, en: "to be (state)", es: "estar", nl: "zijn", type: "verb", ex: { es: "Estoy cansado.", nl: "Ik ben moe." } },
  { id: 53, en: "to have", es: "tener", nl: "hebben", type: "verb", ex: { es: "Tengo dos hermanos.", nl: "Ik heb twee broers." } },
  { id: 54, en: "to do, to make", es: "hacer", nl: "doen, maken", type: "verb", ex: { es: "¿Qué haces?", nl: "Wat doe je?" } },
  { id: 55, en: "to go", es: "ir", nl: "gaan", type: "verb", ex: { es: "Voy al supermercado.", nl: "Ik ga naar de supermarkt." } },
  { id: 56, en: "to come", es: "venir", nl: "komen", type: "verb", ex: { es: "Ven aquí, por favor.", nl: "Kom hier, alsjeblieft." } },
  { id: 57, en: "to say, to tell", es: "decir", nl: "zeggen", type: "verb", ex: { es: "¿Qué quieres decir?", nl: "Wat wil je zeggen?" } },
  { id: 58, en: "to see", es: "ver", nl: "zien", type: "verb", ex: { es: "Puedo ver las montañas.", nl: "Ik kan de bergen zien." } },
  { id: 59, en: "to know (fact)", es: "saber", nl: "weten", type: "verb", ex: { es: "No sé la respuesta.", nl: "Ik weet het antwoord niet." } },
  { id: 60, en: "to know (person)", es: "conocer", nl: "kennen", type: "verb", ex: { es: "¿Conoces a María?", nl: "Ken je Maria?" } },
  { id: 61, en: "to want", es: "querer", nl: "willen", type: "verb", ex: { es: "Quiero aprender holandés.", nl: "Ik wil Spaans leren." } },
  { id: 62, en: "to be able to, can", es: "poder", nl: "kunnen", type: "verb", ex: { es: "¿Puedes ayudarme?", nl: "Kun je me helpen?" } },
  { id: 63, en: "to give", es: "dar", nl: "geven", type: "verb", ex: { es: "Dame un momento.", nl: "Geef me een moment." } },
  { id: 64, en: "to take", es: "tomar", nl: "nemen / pakken", type: "verb", ex: { es: "Toma asiento, por favor.", nl: "Neem plaats, alsjeblieft." } },
  { id: 65, en: "to eat", es: "comer", nl: "eten", type: "verb", ex: { es: "Vamos a comer juntos.", nl: "Laten we samen eten." } },
  { id: 66, en: "to drink", es: "beber", nl: "drinken", type: "verb", ex: { es: "Quiero beber agua.", nl: "Ik wil water drinken." } },
  { id: 67, en: "to speak, to talk", es: "hablar", nl: "spreken, praten", type: "verb", ex: { es: "¿Hablas español?", nl: "Spreek je Nederlands?" } },
  { id: 68, en: "to think", es: "pensar", nl: "denken", type: "verb", ex: { es: "Pienso que es verdad.", nl: "Ik denk dat het waar is." } },
  { id: 69, en: "to find", es: "encontrar", nl: "vinden", type: "verb", ex: { es: "No puedo encontrar mis llaves.", nl: "Ik kan mijn sleutels niet vinden." } },
  { id: 70, en: "to look at, to watch", es: "mirar", nl: "kijken", type: "verb", ex: { es: "Mira el cielo.", nl: "Kijk naar de lucht." } },
  { id: 71, en: "to listen, to hear", es: "escuchar / oír", nl: "luisteren / horen", type: "verb", ex: { es: "Escucha esta canción.", nl: "Luister naar dit lied." } },
  { id: 72, en: "to write", es: "escribir", nl: "schrijven", type: "verb", ex: { es: "Necesito escribir una carta.", nl: "Ik moet een brief schrijven." } },
  { id: 73, en: "to read", es: "leer", nl: "lezen", type: "verb", ex: { es: "Me gusta leer novelas.", nl: "Ik lees graag romans." } },
  { id: 74, en: "to understand", es: "entender", nl: "begrijpen", type: "verb", ex: { es: "No entiendo esta palabra.", nl: "Ik begrijp dit woord niet." } },
  { id: 75, en: "to learn", es: "aprender", nl: "leren", type: "verb", ex: { es: "Quiero aprender a cocinar.", nl: "Ik wil leren koken." } },
  { id: 76, en: "to work", es: "trabajar", nl: "werken", type: "verb", ex: { es: "Trabajo en una oficina.", nl: "Ik werk op een kantoor." } },
  { id: 77, en: "to need", es: "necesitar", nl: "nodig hebben", type: "verb", ex: { es: "Necesito tu ayuda.", nl: "Ik heb je hulp nodig." } },
  { id: 78, en: "to live", es: "vivir", nl: "wonen / leven", type: "verb", ex: { es: "Vivo en una ciudad grande.", nl: "Ik woon in een grote stad." } },
  { id: 79, en: "to believe", es: "creer", nl: "geloven", type: "verb", ex: { es: "Creo que tienes razón.", nl: "Ik geloof dat je gelijk hebt." } },
  { id: 80, en: "to leave", es: "salir", nl: "vertrekken / weggaan", type: "verb", ex: { es: "Salgo de casa a las ocho.", nl: "Ik vertrek om acht uur." } },
  { id: 81, en: "to arrive", es: "llegar", nl: "aankomen", type: "verb", ex: { es: "Llegamos tarde.", nl: "We komen te laat aan." } },
  { id: 82, en: "to put, to place", es: "poner", nl: "zetten / leggen", type: "verb", ex: { es: "Pon el libro en la mesa.", nl: "Leg het boek op de tafel." } },
  { id: 83, en: "to wait", es: "esperar", nl: "wachten", type: "verb", ex: { es: "Espérame un momento.", nl: "Wacht even op mij." } },
  { id: 84, en: "to feel", es: "sentir", nl: "voelen", type: "verb", ex: { es: "Me siento feliz.", nl: "Ik voel me gelukkig." } },
  { id: 85, en: "to sleep", es: "dormir", nl: "slapen", type: "verb", ex: { es: "Necesito dormir más.", nl: "Ik moet meer slapen." } },
  { id: 86, en: "to buy", es: "comprar", nl: "kopen", type: "verb", ex: { es: "Voy a comprar pan.", nl: "Ik ga brood kopen." } },
  { id: 87, en: "to sell", es: "vender", nl: "verkopen", type: "verb", ex: { es: "Quiero vender mi coche.", nl: "Ik wil mijn auto verkopen." } },
  { id: 88, en: "to pay", es: "pagar", nl: "betalen", type: "verb", ex: { es: "¿Puedo pagar con tarjeta?", nl: "Kan ik met de kaart betalen?" } },
  { id: 89, en: "to open", es: "abrir", nl: "openen / opendoen", type: "verb", ex: { es: "Abre la puerta.", nl: "Doe de deur open." } },
  { id: 90, en: "to close", es: "cerrar", nl: "sluiten / dichtdoen", type: "verb", ex: { es: "Cierra la ventana.", nl: "Doe het raam dicht." } },
  { id: 91, en: "to begin, to start", es: "empezar / comenzar", nl: "beginnen", type: "verb", ex: { es: "La clase empieza a las nueve.", nl: "De les begint om negen uur." } },
  { id: 92, en: "to finish, to end", es: "terminar / acabar", nl: "eindigen / afmaken", type: "verb", ex: { es: "Terminé mi trabajo.", nl: "Ik heb mijn werk afgemaakt." } },
  { id: 93, en: "to walk", es: "caminar / andar", nl: "lopen / wandelen", type: "verb", ex: { es: "Me gusta caminar por el parque.", nl: "Ik loop graag door het park." } },
  { id: 94, en: "to run", es: "correr", nl: "rennen / hardlopen", type: "verb", ex: { es: "Los niños corren en el jardín.", nl: "De kinderen rennen in de tuin." } },
  { id: 95, en: "to drive", es: "conducir", nl: "rijden", type: "verb", ex: { es: "¿Sabes conducir?", nl: "Kun je rijden?" } },
  { id: 96, en: "to play", es: "jugar", nl: "spelen", type: "verb", ex: { es: "Los niños juegan en el parque.", nl: "De kinderen spelen in het park." } },
  { id: 97, en: "to help", es: "ayudar", nl: "helpen", type: "verb", ex: { es: "¿Me puedes ayudar?", nl: "Kun je me helpen?" } },
  { id: 98, en: "to try", es: "intentar / probar", nl: "proberen", type: "verb", ex: { es: "Voy a intentar otra vez.", nl: "Ik ga het opnieuw proberen." } },
  { id: 99, en: "to use", es: "usar / utilizar", nl: "gebruiken", type: "verb", ex: { es: "¿Puedo usar tu teléfono?", nl: "Mag ik je telefoon gebruiken?" } },
  { id: 100, en: "to call", es: "llamar", nl: "bellen / noemen", type: "verb", ex: { es: "Te llamo mañana.", nl: "Ik bel je morgen." } },
  { id: 101, en: "to ask", es: "preguntar / pedir", nl: "vragen", type: "verb", ex: { es: "Quiero preguntar algo.", nl: "Ik wil iets vragen." } },
  { id: 102, en: "to answer", es: "responder / contestar", nl: "antwoorden", type: "verb", ex: { es: "No puedo responder ahora.", nl: "Ik kan nu niet antwoorden." } },
  { id: 103, en: "to remember", es: "recordar", nl: "onthouden / herinneren", type: "verb", ex: { es: "No recuerdo su nombre.", nl: "Ik kan zijn naam niet onthouden." } },
  { id: 104, en: "to forget", es: "olvidar", nl: "vergeten", type: "verb", ex: { es: "No olvides tu pasaporte.", nl: "Vergeet je paspoort niet." } },
  { id: 105, en: "to love", es: "amar / querer", nl: "houden van", type: "verb", ex: { es: "Te amo.", nl: "Ik hou van je." } },
  { id: 106, en: "to like", es: "gustar", nl: "leuk vinden", type: "verb", ex: { es: "Me gusta el chocolate.", nl: "Ik vind chocolade lekker." } },
  { id: 107, en: "to hate", es: "odiar", nl: "haten", type: "verb", ex: { es: "Odio levantarme temprano.", nl: "Ik haat vroeg opstaan." } },
  { id: 108, en: "to send", es: "enviar / mandar", nl: "sturen / verzenden", type: "verb", ex: { es: "Te envío un mensaje.", nl: "Ik stuur je een bericht." } },
  { id: 109, en: "to receive", es: "recibir", nl: "ontvangen", type: "verb", ex: { es: "Recibí tu carta.", nl: "Ik heb je brief ontvangen." } },
  { id: 110, en: "to bring", es: "traer", nl: "meebrengen", type: "verb", ex: { es: "Trae tu libro.", nl: "Breng je boek mee." } },
  { id: 111, en: "to carry, to wear", es: "llevar", nl: "dragen / meenemen", type: "verb", ex: { es: "Llevo una camisa azul.", nl: "Ik draag een blauw shirt." } },
  { id: 112, en: "to return", es: "volver / regresar", nl: "terugkomen / terugkeren", type: "verb", ex: { es: "Vuelvo enseguida.", nl: "Ik kom zo terug." } },
  { id: 113, en: "to change", es: "cambiar", nl: "veranderen / wisselen", type: "verb", ex: { es: "Quiero cambiar de tema.", nl: "Ik wil van onderwerp veranderen." } },
  { id: 114, en: "to choose", es: "elegir / escoger", nl: "kiezen", type: "verb", ex: { es: "Elige el que prefieras.", nl: "Kies degene die je wilt." } },
  { id: 115, en: "to show", es: "mostrar / enseñar", nl: "laten zien / tonen", type: "verb", ex: { es: "Muéstrame el camino.", nl: "Laat me de weg zien." } },
  { id: 116, en: "to teach", es: "enseñar", nl: "lesgeven / onderwijzen", type: "verb", ex: { es: "Ella enseña matemáticas.", nl: "Zij geeft les in wiskunde." } },
  { id: 117, en: "to sing", es: "cantar", nl: "zingen", type: "verb", ex: { es: "Le gusta cantar.", nl: "Hij zingt graag." } },
  { id: 118, en: "to cook", es: "cocinar", nl: "koken", type: "verb", ex: { es: "Mi madre cocina muy bien.", nl: "Mijn moeder kookt heel goed." } },
  { id: 119, en: "to wash", es: "lavar", nl: "wassen", type: "verb", ex: { es: "Voy a lavar los platos.", nl: "Ik ga de borden wassen." } },
  { id: 120, en: "to clean", es: "limpiar", nl: "schoonmaken", type: "verb", ex: { es: "Hay que limpiar la casa.", nl: "We moeten het huis schoonmaken." } },
  { id: 121, en: "to sit (down)", es: "sentarse", nl: "gaan zitten", type: "verb", ex: { es: "Siéntate aquí.", nl: "Ga hier zitten." } },
  { id: 122, en: "to stand (up)", es: "levantarse", nl: "opstaan", type: "verb", ex: { es: "Levántate temprano.", nl: "Sta vroeg op." } },
  { id: 123, en: "to fly", es: "volar", nl: "vliegen", type: "verb", ex: { es: "Los pájaros vuelan alto.", nl: "De vogels vliegen hoog." } },
  { id: 124, en: "to swim", es: "nadar", nl: "zwemmen", type: "verb", ex: { es: "Me gusta nadar en el mar.", nl: "Ik zwem graag in de zee." } },
  { id: 125, en: "to fall", es: "caer", nl: "vallen", type: "verb", ex: { es: "Las hojas caen en otoño.", nl: "De bladeren vallen in de herfst." } },
  { id: 126, en: "to break", es: "romper", nl: "breken / kapotmaken", type: "verb", ex: { es: "Se rompió el vaso.", nl: "Het glas is gebroken." } },
  { id: 127, en: "to build", es: "construir", nl: "bouwen", type: "verb", ex: { es: "Van a construir un puente.", nl: "Ze gaan een brug bouwen." } },
  { id: 128, en: "to grow", es: "crecer", nl: "groeien", type: "verb", ex: { es: "Las plantas crecen rápido.", nl: "De planten groeien snel." } },
  { id: 129, en: "to die", es: "morir", nl: "sterven / doodgaan", type: "verb", ex: { es: "Las flores mueren en invierno.", nl: "De bloemen sterven in de winter." } },
  { id: 130, en: "to win", es: "ganar", nl: "winnen", type: "verb", ex: { es: "Quiero ganar el partido.", nl: "Ik wil de wedstrijd winnen." } },
  { id: 131, en: "to lose", es: "perder", nl: "verliezen", type: "verb", ex: { es: "Perdí mi cartera.", nl: "Ik ben mijn portemonnee verloren." } },
  { id: 132, en: "to enter", es: "entrar", nl: "binnenkomen", type: "verb", ex: { es: "Entra en la habitación.", nl: "Kom de kamer binnen." } },
  { id: 133, en: "to leave, to exit", es: "salir", nl: "vertrekken / uitgaan", type: "verb", ex: { es: "Vamos a salir esta noche.", nl: "We gaan vanavond uit." } },
  { id: 134, en: "to stop", es: "parar / detener", nl: "stoppen", type: "verb", ex: { es: "Para el coche aquí.", nl: "Stop de auto hier." } },
  { id: 135, en: "to follow", es: "seguir", nl: "volgen", type: "verb", ex: { es: "Sigue todo recto.", nl: "Ga rechtdoor." } },
  { id: 136, en: "to move", es: "mover", nl: "bewegen / verhuizen", type: "verb", ex: { es: "No te muevas.", nl: "Niet bewegen." } },
  { id: 137, en: "to turn", es: "girar / voltear", nl: "draaien / afslaan", type: "verb", ex: { es: "Gira a la derecha.", nl: "Sla rechtsaf." } },
  { id: 138, en: "to meet", es: "conocer / encontrarse", nl: "ontmoeten", type: "verb", ex: { es: "Encantado de conocerte.", nl: "Leuk je te ontmoeten." } },
  { id: 139, en: "to happen", es: "pasar / ocurrir", nl: "gebeuren", type: "verb", ex: { es: "¿Qué pasó?", nl: "Wat is er gebeurd?" } },
  { id: 140, en: "to seem, to appear", es: "parecer", nl: "lijken / schijnen", type: "verb", ex: { es: "Parece fácil.", nl: "Het lijkt makkelijk." } },
  { id: 141, en: "to must, to have to", es: "deber / tener que", nl: "moeten", type: "verb", ex: { es: "Debo estudiar más.", nl: "Ik moet meer studeren." } },
  { id: 142, en: "to hope, to wish", es: "esperar / desear", nl: "hopen", type: "verb", ex: { es: "Espero que todo salga bien.", nl: "Ik hoop dat alles goed gaat." } },
  { id: 143, en: "to cost", es: "costar", nl: "kosten", type: "verb", ex: { es: "¿Cuánto cuesta esto?", nl: "Hoeveel kost dit?" } },
  { id: 144, en: "to cut", es: "cortar", nl: "snijden / knippen", type: "verb", ex: { es: "Corta el pan.", nl: "Snijd het brood." } },
  { id: 145, en: "to accept", es: "aceptar", nl: "accepteren", type: "verb", ex: { es: "Acepto tu invitación.", nl: "Ik accepteer je uitnodiging." } },
  { id: 146, en: "to explain", es: "explicar", nl: "uitleggen", type: "verb", ex: { es: "¿Puedes explicar esto?", nl: "Kun je dit uitleggen?" } },
  { id: 147, en: "to share", es: "compartir", nl: "delen", type: "verb", ex: { es: "Quiero compartir contigo.", nl: "Ik wil met je delen." } },
  { id: 148, en: "to prepare", es: "preparar", nl: "voorbereiden / klaarmaken", type: "verb", ex: { es: "Voy a preparar la cena.", nl: "Ik ga het avondeten klaarmaken." } },
  { id: 149, en: "to decide", es: "decidir", nl: "beslissen / besluiten", type: "verb", ex: { es: "Tienes que decidir.", nl: "Je moet beslissen." } },
  { id: 150, en: "to pass, to spend (time)", es: "pasar", nl: "doorbrengen / voorbijgaan", type: "verb", ex: { es: "Pasamos el verano en la playa.", nl: "We brengen de zomer op het strand door." } },

  // ── 151–250: Common Nouns ───────────────────────────────────────
  { id: 151, en: "time", es: "tiempo", nl: "tijd", type: "noun", g: "m", ex: { es: "No tengo tiempo.", nl: "Ik heb geen tijd." } },
  { id: 152, en: "day", es: "día", nl: "dag", type: "noun", g: "m", ex: { es: "Hoy es un buen día.", nl: "Vandaag is een goede dag." } },
  { id: 153, en: "year", es: "año", nl: "jaar", type: "noun", g: "m", ex: { es: "Este año viajo a Francia.", nl: "Dit jaar reis ik naar Frankrijk." } },
  { id: 154, en: "person", es: "persona", nl: "persoon", type: "noun", g: "f", ex: { es: "Es una buena persona.", nl: "Het is een goed persoon." } },
  { id: 155, en: "man", es: "hombre", nl: "man", type: "noun", g: "m", ex: { es: "El hombre lee un libro.", nl: "De man leest een boek." } },
  { id: 156, en: "woman", es: "mujer", nl: "vrouw", type: "noun", g: "f", ex: { es: "La mujer canta una canción.", nl: "De vrouw zingt een lied." } },
  { id: 157, en: "child, boy", es: "niño", nl: "kind, jongen", type: "noun", g: "m", ex: { es: "El niño juega con la pelota.", nl: "Het kind speelt met de bal." } },
  { id: 158, en: "girl", es: "niña / chica", nl: "meisje", type: "noun", g: "f", ex: { es: "La niña dibuja una casa.", nl: "Het meisje tekent een huis." } },
  { id: 159, en: "house, home", es: "casa", nl: "huis", type: "noun", g: "f", ex: { es: "Mi casa es pequeña.", nl: "Mijn huis is klein." } },
  { id: 160, en: "water", es: "agua", nl: "water", type: "noun", g: "f", ex: { es: "El agua está fría.", nl: "Het water is koud." } },
  { id: 161, en: "food", es: "comida", nl: "eten / voedsel", type: "noun", g: "f", ex: { es: "La comida está lista.", nl: "Het eten is klaar." } },
  { id: 162, en: "work, job", es: "trabajo", nl: "werk / baan", type: "noun", g: "m", ex: { es: "Tengo mucho trabajo.", nl: "Ik heb veel werk." } },
  { id: 163, en: "money", es: "dinero", nl: "geld", type: "noun", g: "m", ex: { es: "No tengo dinero.", nl: "Ik heb geen geld." } },
  { id: 164, en: "world", es: "mundo", nl: "wereld", type: "noun", g: "m", ex: { es: "El mundo es grande.", nl: "De wereld is groot." } },
  { id: 165, en: "country", es: "país", nl: "land", type: "noun", g: "m", ex: { es: "España es un país bonito.", nl: "Nederland is een mooi land." } },
  { id: 166, en: "city", es: "ciudad", nl: "stad", type: "noun", g: "f", ex: { es: "Vivo en una ciudad grande.", nl: "Ik woon in een grote stad." } },
  { id: 167, en: "life", es: "vida", nl: "leven", type: "noun", g: "f", ex: { es: "La vida es bella.", nl: "Het leven is mooi." } },
  { id: 168, en: "name", es: "nombre", nl: "naam", type: "noun", g: "m", ex: { es: "¿Cuál es tu nombre?", nl: "Wat is je naam?" } },
  { id: 169, en: "friend", es: "amigo / amiga", nl: "vriend / vriendin", type: "noun", g: "m", ex: { es: "Ella es mi mejor amiga.", nl: "Zij is mijn beste vriendin." } },
  { id: 170, en: "family", es: "familia", nl: "familie / gezin", type: "noun", g: "f", ex: { es: "Mi familia es grande.", nl: "Mijn familie is groot." } },
  { id: 171, en: "father", es: "padre", nl: "vader", type: "noun", g: "m", ex: { es: "Mi padre trabaja mucho.", nl: "Mijn vader werkt veel." } },
  { id: 172, en: "mother", es: "madre", nl: "moeder", type: "noun", g: "f", ex: { es: "Mi madre cocina muy bien.", nl: "Mijn moeder kookt heel goed." } },
  { id: 173, en: "brother", es: "hermano", nl: "broer", type: "noun", g: "m", ex: { es: "Tengo un hermano mayor.", nl: "Ik heb een oudere broer." } },
  { id: 174, en: "sister", es: "hermana", nl: "zus", type: "noun", g: "f", ex: { es: "Mi hermana vive en París.", nl: "Mijn zus woont in Parijs." } },
  { id: 175, en: "son", es: "hijo", nl: "zoon", type: "noun", g: "m", ex: { es: "Mi hijo tiene tres años.", nl: "Mijn zoon is drie jaar oud." } },
  { id: 176, en: "daughter", es: "hija", nl: "dochter", type: "noun", g: "f", ex: { es: "Mi hija estudia medicina.", nl: "Mijn dochter studeert geneeskunde." } },
  { id: 177, en: "book", es: "libro", nl: "boek", type: "noun", g: "m", ex: { es: "Este libro es interesante.", nl: "Dit boek is interessant." } },
  { id: 178, en: "word", es: "palabra", nl: "woord", type: "noun", g: "f", ex: { es: "No entiendo esta palabra.", nl: "Ik begrijp dit woord niet." } },
  { id: 179, en: "question", es: "pregunta", nl: "vraag", type: "noun", g: "f", ex: { es: "Tengo una pregunta.", nl: "Ik heb een vraag." } },
  { id: 180, en: "answer", es: "respuesta", nl: "antwoord", type: "noun", g: "f", ex: { es: "No sé la respuesta.", nl: "Ik weet het antwoord niet." } },
  { id: 181, en: "school", es: "escuela / colegio", nl: "school", type: "noun", g: "f", ex: { es: "Los niños van a la escuela.", nl: "De kinderen gaan naar school." } },
  { id: 182, en: "street", es: "calle", nl: "straat", type: "noun", g: "f", ex: { es: "Vivo en esa calle.", nl: "Ik woon in die straat." } },
  { id: 183, en: "car", es: "coche / carro", nl: "auto", type: "noun", g: "m", ex: { es: "Mi coche es rojo.", nl: "Mijn auto is rood." } },
  { id: 184, en: "door", es: "puerta", nl: "deur", type: "noun", g: "f", ex: { es: "Abre la puerta.", nl: "Doe de deur open." } },
  { id: 185, en: "window", es: "ventana", nl: "raam", type: "noun", g: "f", ex: { es: "Cierra la ventana.", nl: "Doe het raam dicht." } },
  { id: 186, en: "table", es: "mesa", nl: "tafel", type: "noun", g: "f", ex: { es: "La mesa está lista.", nl: "De tafel is gedekt." } },
  { id: 187, en: "chair", es: "silla", nl: "stoel", type: "noun", g: "f", ex: { es: "Siéntate en la silla.", nl: "Ga op de stoel zitten." } },
  { id: 188, en: "bed", es: "cama", nl: "bed", type: "noun", g: "f", ex: { es: "Voy a la cama.", nl: "Ik ga naar bed." } },
  { id: 189, en: "kitchen", es: "cocina", nl: "keuken", type: "noun", g: "f", ex: { es: "La cocina es grande.", nl: "De keuken is groot." } },
  { id: 190, en: "bathroom", es: "baño", nl: "badkamer", type: "noun", g: "m", ex: { es: "¿Dónde está el baño?", nl: "Waar is de badkamer?" } },
  { id: 191, en: "road, way", es: "camino", nl: "weg", type: "noun", g: "m", ex: { es: "Conoce el camino.", nl: "Hij kent de weg." } },
  { id: 192, en: "store, shop", es: "tienda", nl: "winkel", type: "noun", g: "f", ex: { es: "Voy a la tienda.", nl: "Ik ga naar de winkel." } },
  { id: 193, en: "morning", es: "mañana", nl: "ochtend / morgen", type: "noun", g: "f", ex: { es: "Buenos días. Es por la mañana.", nl: "Goedemorgen. Het is ochtend." } },
  { id: 194, en: "afternoon", es: "tarde", nl: "middag", type: "noun", g: "f", ex: { es: "Buenas tardes.", nl: "Goedemiddag." } },
  { id: 195, en: "night", es: "noche", nl: "nacht / avond", type: "noun", g: "f", ex: { es: "Buenas noches.", nl: "Goedenavond." } },
  { id: 196, en: "week", es: "semana", nl: "week", type: "noun", g: "f", ex: { es: "La próxima semana tengo examen.", nl: "Volgende week heb ik een examen." } },
  { id: 197, en: "month", es: "mes", nl: "maand", type: "noun", g: "m", ex: { es: "Este mes es octubre.", nl: "Deze maand is oktober." } },
  { id: 198, en: "hour", es: "hora", nl: "uur", type: "noun", g: "f", ex: { es: "¿Qué hora es?", nl: "Hoe laat is het?" } },
  { id: 199, en: "minute", es: "minuto", nl: "minuut", type: "noun", g: "m", ex: { es: "Espera un minuto.", nl: "Wacht een minuut." } },
  { id: 200, en: "hand", es: "mano", nl: "hand", type: "noun", g: "f", ex: { es: "Dame la mano.", nl: "Geef me je hand." } },
  { id: 201, en: "head", es: "cabeza", nl: "hoofd", type: "noun", g: "f", ex: { es: "Me duele la cabeza.", nl: "Ik heb hoofdpijn." } },
  { id: 202, en: "eye", es: "ojo", nl: "oog", type: "noun", g: "m", ex: { es: "Tiene ojos azules.", nl: "Hij heeft blauwe ogen." } },
  { id: 203, en: "heart", es: "corazón", nl: "hart", type: "noun", g: "m", ex: { es: "Escucha a tu corazón.", nl: "Luister naar je hart." } },
  { id: 204, en: "mouth", es: "boca", nl: "mond", type: "noun", g: "f", ex: { es: "Abre la boca.", nl: "Doe je mond open." } },
  { id: 205, en: "ear", es: "oreja / oído", nl: "oor", type: "noun", g: "f", ex: { es: "No puedo oír bien.", nl: "Ik kan niet goed horen." } },
  { id: 206, en: "nose", es: "nariz", nl: "neus", type: "noun", g: "f", ex: { es: "Tiene la nariz roja.", nl: "Zijn neus is rood." } },
  { id: 207, en: "foot", es: "pie", nl: "voet", type: "noun", g: "m", ex: { es: "Me duele el pie.", nl: "Mijn voet doet pijn." } },
  { id: 208, en: "body", es: "cuerpo", nl: "lichaam", type: "noun", g: "m", ex: { es: "El cuerpo humano es complejo.", nl: "Het menselijk lichaam is complex." } },
  { id: 209, en: "dog", es: "perro", nl: "hond", type: "noun", g: "m", ex: { es: "El perro ladra mucho.", nl: "De hond blaft veel." } },
  { id: 210, en: "cat", es: "gato", nl: "kat", type: "noun", g: "m", ex: { es: "El gato duerme en el sofá.", nl: "De kat slaapt op de bank." } },
  { id: 211, en: "tree", es: "árbol", nl: "boom", type: "noun", g: "m", ex: { es: "El árbol es muy alto.", nl: "De boom is heel hoog." } },
  { id: 212, en: "flower", es: "flor", nl: "bloem", type: "noun", g: "f", ex: { es: "Las flores son bonitas.", nl: "De bloemen zijn mooi." } },
  { id: 213, en: "sun", es: "sol", nl: "zon", type: "noun", g: "m", ex: { es: "El sol brilla hoy.", nl: "De zon schijnt vandaag." } },
  { id: 214, en: "moon", es: "luna", nl: "maan", type: "noun", g: "f", ex: { es: "La luna está llena.", nl: "De maan is vol." } },
  { id: 215, en: "star", es: "estrella", nl: "ster", type: "noun", g: "f", ex: { es: "Las estrellas brillan de noche.", nl: "De sterren schijnen 's nachts." } },
  { id: 216, en: "sky", es: "cielo", nl: "lucht / hemel", type: "noun", g: "m", ex: { es: "El cielo está azul.", nl: "De lucht is blauw." } },
  { id: 217, en: "sea, ocean", es: "mar", nl: "zee", type: "noun", g: "m", ex: { es: "El mar está tranquilo.", nl: "De zee is rustig." } },
  { id: 218, en: "mountain", es: "montaña", nl: "berg", type: "noun", g: "f", ex: { es: "Subimos la montaña.", nl: "We beklimmen de berg." } },
  { id: 219, en: "river", es: "río", nl: "rivier", type: "noun", g: "m", ex: { es: "El río es muy largo.", nl: "De rivier is heel lang." } },
  { id: 220, en: "rain", es: "lluvia", nl: "regen", type: "noun", g: "f", ex: { es: "La lluvia es fuerte hoy.", nl: "De regen is sterk vandaag." } },
  { id: 221, en: "snow", es: "nieve", nl: "sneeuw", type: "noun", g: "f", ex: { es: "La nieve cubre las montañas.", nl: "De sneeuw bedekt de bergen." } },
  { id: 222, en: "wind", es: "viento", nl: "wind", type: "noun", g: "m", ex: { es: "El viento sopla fuerte.", nl: "De wind waait hard." } },
  { id: 223, en: "fire", es: "fuego", nl: "vuur", type: "noun", g: "m", ex: { es: "¡Cuidado con el fuego!", nl: "Pas op voor het vuur!" } },
  { id: 224, en: "earth, ground", es: "tierra", nl: "aarde / grond", type: "noun", g: "f", ex: { es: "La tierra es fértil.", nl: "De grond is vruchtbaar." } },
  { id: 225, en: "air", es: "aire", nl: "lucht", type: "noun", g: "m", ex: { es: "El aire está limpio aquí.", nl: "De lucht is schoon hier." } },
  { id: 226, en: "bread", es: "pan", nl: "brood", type: "noun", g: "m", ex: { es: "Compro pan cada día.", nl: "Ik koop elke dag brood." } },
  { id: 227, en: "meat", es: "carne", nl: "vlees", type: "noun", g: "f", ex: { es: "No como carne.", nl: "Ik eet geen vlees." } },
  { id: 228, en: "fish", es: "pescado / pez", nl: "vis", type: "noun", g: "m", ex: { es: "El pescado está fresco.", nl: "De vis is vers." } },
  { id: 229, en: "milk", es: "leche", nl: "melk", type: "noun", g: "f", ex: { es: "Quiero un vaso de leche.", nl: "Ik wil een glas melk." } },
  { id: 230, en: "fruit", es: "fruta", nl: "fruit", type: "noun", g: "f", ex: { es: "La fruta es saludable.", nl: "Fruit is gezond." } },
  { id: 231, en: "coffee", es: "café", nl: "koffie", type: "noun", g: "m", ex: { es: "Quiero un café, por favor.", nl: "Ik wil koffie, alsjeblieft." } },
  { id: 232, en: "tea", es: "té", nl: "thee", type: "noun", g: "m", ex: { es: "¿Quieres una taza de té?", nl: "Wil je een kopje thee?" } },
  { id: 233, en: "beer", es: "cerveza", nl: "bier", type: "noun", g: "f", ex: { es: "Una cerveza, por favor.", nl: "Een biertje, alsjeblieft." } },
  { id: 234, en: "wine", es: "vino", nl: "wijn", type: "noun", g: "m", ex: { es: "Este vino es excelente.", nl: "Deze wijn is uitstekend." } },
  { id: 235, en: "sugar", es: "azúcar", nl: "suiker", type: "noun", g: "m", ex: { es: "¿Quieres azúcar?", nl: "Wil je suiker?" } },
  { id: 236, en: "salt", es: "sal", nl: "zout", type: "noun", g: "f", ex: { es: "Pásame la sal.", nl: "Geef me het zout." } },
  { id: 237, en: "egg", es: "huevo", nl: "ei", type: "noun", g: "m", ex: { es: "Quiero un huevo frito.", nl: "Ik wil een gebakken ei." } },
  { id: 238, en: "cheese", es: "queso", nl: "kaas", type: "noun", g: "m", ex: { es: "Me gusta el queso.", nl: "Ik hou van kaas." } },
  { id: 239, en: "rice", es: "arroz", nl: "rijst", type: "noun", g: "m", ex: { es: "El arroz está listo.", nl: "De rijst is klaar." } },
  { id: 240, en: "chicken", es: "pollo", nl: "kip", type: "noun", g: "m", ex: { es: "El pollo con arroz es rico.", nl: "Kip met rijst is lekker." } },
  { id: 241, en: "letter", es: "carta / letra", nl: "brief / letter", type: "noun", g: "f", ex: { es: "Escribí una carta.", nl: "Ik heb een brief geschreven." } },
  { id: 242, en: "number", es: "número", nl: "nummer / getal", type: "noun", g: "m", ex: { es: "Dame tu número de teléfono.", nl: "Geef me je telefoonnummer." } },
  { id: 243, en: "language", es: "idioma / lengua", nl: "taal", type: "noun", g: "m", ex: { es: "Hablo tres idiomas.", nl: "Ik spreek drie talen." } },
  { id: 244, en: "music", es: "música", nl: "muziek", type: "noun", g: "f", ex: { es: "Me gusta la música.", nl: "Ik hou van muziek." } },
  { id: 245, en: "movie, film", es: "película", nl: "film", type: "noun", g: "f", ex: { es: "La película es buena.", nl: "De film is goed." } },
  { id: 246, en: "game", es: "juego", nl: "spel", type: "noun", g: "m", ex: { es: "¿Quieres jugar un juego?", nl: "Wil je een spelletje spelen?" } },
  { id: 247, en: "problem", es: "problema", nl: "probleem", type: "noun", g: "m", ex: { es: "No hay problema.", nl: "Geen probleem." } },
  { id: 248, en: "idea", es: "idea", nl: "idee", type: "noun", g: "f", ex: { es: "Tengo una idea.", nl: "Ik heb een idee." } },
  { id: 249, en: "thing", es: "cosa", nl: "ding", type: "noun", g: "f", ex: { es: "¿Qué es esa cosa?", nl: "Wat is dat ding?" } },
  { id: 250, en: "place", es: "lugar / sitio", nl: "plaats / plek", type: "noun", g: "m", ex: { es: "Es un lugar bonito.", nl: "Het is een mooie plek." } },

  // ── 251–350: More Nouns (themed) ────────────────────────────────
  { id: 251, en: "king", es: "rey", nl: "koning", type: "noun", g: "m", ex: { es: "El rey vive en el palacio.", nl: "De koning woont in het paleis." } },
  { id: 252, en: "doctor", es: "médico / doctor", nl: "dokter / arts", type: "noun", g: "m", ex: { es: "Necesito ver a un médico.", nl: "Ik moet naar de dokter." } },
  { id: 253, en: "teacher", es: "profesor", nl: "leraar / docent", type: "noun", g: "m", ex: { es: "El profesor es amable.", nl: "De leraar is aardig." } },
  { id: 254, en: "student", es: "estudiante", nl: "student / leerling", type: "noun", g: "m", ex: { es: "Soy estudiante de medicina.", nl: "Ik ben student geneeskunde." } },
  { id: 255, en: "police", es: "policía", nl: "politie", type: "noun", g: "m", ex: { es: "Llama a la policía.", nl: "Bel de politie." } },
  { id: 256, en: "market", es: "mercado", nl: "markt", type: "noun", g: "m", ex: { es: "Vamos al mercado.", nl: "We gaan naar de markt." } },
  { id: 257, en: "church", es: "iglesia", nl: "kerk", type: "noun", g: "f", ex: { es: "La iglesia es antigua.", nl: "De kerk is oud." } },
  { id: 258, en: "hospital", es: "hospital", nl: "ziekenhuis", type: "noun", g: "m", ex: { es: "Trabaja en el hospital.", nl: "Hij werkt in het ziekenhuis." } },
  { id: 259, en: "restaurant", es: "restaurante", nl: "restaurant", type: "noun", g: "m", ex: { es: "Vamos a un restaurante.", nl: "We gaan naar een restaurant." } },
  { id: 260, en: "airport", es: "aeropuerto", nl: "luchthaven / vliegveld", type: "noun", g: "m", ex: { es: "El aeropuerto está lejos.", nl: "De luchthaven is ver weg." } },
  { id: 261, en: "train", es: "tren", nl: "trein", type: "noun", g: "m", ex: { es: "El tren sale a las tres.", nl: "De trein vertrekt om drie uur." } },
  { id: 262, en: "bus", es: "autobús", nl: "bus", type: "noun", g: "m", ex: { es: "El autobús llega tarde.", nl: "De bus komt te laat." } },
  { id: 263, en: "bicycle", es: "bicicleta", nl: "fiets", type: "noun", g: "f", ex: { es: "Voy en bicicleta.", nl: "Ik ga met de fiets." } },
  { id: 264, en: "ticket", es: "billete / boleto", nl: "kaartje", type: "noun", g: "m", ex: { es: "Necesito un billete de tren.", nl: "Ik heb een treinkaartje nodig." } },
  { id: 265, en: "map", es: "mapa", nl: "kaart", type: "noun", g: "m", ex: { es: "¿Tienes un mapa?", nl: "Heb je een kaart?" } },
  { id: 266, en: "room", es: "habitación / cuarto", nl: "kamer", type: "noun", g: "f", ex: { es: "La habitación es grande.", nl: "De kamer is groot." } },
  { id: 267, en: "key", es: "llave", nl: "sleutel", type: "noun", g: "f", ex: { es: "No encuentro mis llaves.", nl: "Ik kan mijn sleutels niet vinden." } },
  { id: 268, en: "phone", es: "teléfono", nl: "telefoon", type: "noun", g: "m", ex: { es: "¿Dónde está mi teléfono?", nl: "Waar is mijn telefoon?" } },
  { id: 269, en: "computer", es: "computadora / ordenador", nl: "computer", type: "noun", g: "f", ex: { es: "Trabajo con el ordenador.", nl: "Ik werk met de computer." } },
  { id: 270, en: "internet", es: "internet", nl: "internet", type: "noun", g: "m", ex: { es: "¿Hay internet aquí?", nl: "Is er internet hier?" } },
  { id: 271, en: "song", es: "canción", nl: "lied / nummer", type: "noun", g: "f", ex: { es: "Esa canción es bonita.", nl: "Dat lied is mooi." } },
  { id: 272, en: "photo", es: "foto", nl: "foto", type: "noun", g: "f", ex: { es: "¿Puedo tomar una foto?", nl: "Mag ik een foto maken?" } },
  { id: 273, en: "paper", es: "papel", nl: "papier", type: "noun", g: "m", ex: { es: "Necesito un papel.", nl: "Ik heb papier nodig." } },
  { id: 274, en: "pen", es: "bolígrafo / pluma", nl: "pen", type: "noun", g: "m", ex: { es: "¿Tienes un bolígrafo?", nl: "Heb je een pen?" } },
  { id: 275, en: "bag", es: "bolsa / bolso", nl: "tas", type: "noun", g: "f", ex: { es: "Mi bolso es negro.", nl: "Mijn tas is zwart." } },
  { id: 276, en: "hat", es: "sombrero / gorra", nl: "hoed / pet", type: "noun", g: "m", ex: { es: "Lleva un sombrero.", nl: "Hij draagt een hoed." } },
  { id: 277, en: "shirt", es: "camisa / camiseta", nl: "shirt / overhemd", type: "noun", g: "f", ex: { es: "Me gusta tu camisa.", nl: "Ik vind je shirt leuk." } },
  { id: 278, en: "shoes", es: "zapatos", nl: "schoenen", type: "noun", g: "m", ex: { es: "Necesito zapatos nuevos.", nl: "Ik heb nieuwe schoenen nodig." } },
  { id: 279, en: "dress", es: "vestido", nl: "jurk", type: "noun", g: "m", ex: { es: "Ese vestido es bonito.", nl: "Die jurk is mooi." } },
  { id: 280, en: "coat", es: "abrigo", nl: "jas", type: "noun", g: "m", ex: { es: "Ponte el abrigo.", nl: "Trek je jas aan." } },
  { id: 281, en: "glasses", es: "gafas / lentes", nl: "bril", type: "noun", g: "f", ex: { es: "Necesito mis gafas.", nl: "Ik heb mijn bril nodig." } },
  { id: 282, en: "clock, watch", es: "reloj", nl: "klok / horloge", type: "noun", g: "m", ex: { es: "¿Qué hora marca el reloj?", nl: "Hoe laat is het op de klok?" } },
  { id: 283, en: "gift, present", es: "regalo", nl: "cadeau", type: "noun", g: "m", ex: { es: "Es un regalo para ti.", nl: "Het is een cadeau voor jou." } },
  { id: 284, en: "piece", es: "pieza / pedazo", nl: "stuk", type: "noun", g: "f", ex: { es: "Quiero un pedazo de pastel.", nl: "Ik wil een stuk taart." } },
  { id: 285, en: "plate, dish", es: "plato", nl: "bord", type: "noun", g: "m", ex: { es: "El plato está caliente.", nl: "Het bord is heet." } },
  { id: 286, en: "cup, glass", es: "vaso / taza", nl: "glas / kopje", type: "noun", g: "m", ex: { es: "Dame un vaso de agua.", nl: "Geef me een glas water." } },
  { id: 287, en: "bottle", es: "botella", nl: "fles", type: "noun", g: "f", ex: { es: "La botella está vacía.", nl: "De fles is leeg." } },
  { id: 288, en: "garden", es: "jardín", nl: "tuin", type: "noun", g: "m", ex: { es: "El jardín tiene flores.", nl: "De tuin heeft bloemen." } },
  { id: 289, en: "park", es: "parque", nl: "park", type: "noun", g: "m", ex: { es: "Vamos al parque.", nl: "We gaan naar het park." } },
  { id: 290, en: "beach", es: "playa", nl: "strand", type: "noun", g: "f", ex: { es: "Vamos a la playa.", nl: "We gaan naar het strand." } },
  { id: 291, en: "island", es: "isla", nl: "eiland", type: "noun", g: "f", ex: { es: "La isla es pequeña.", nl: "Het eiland is klein." } },
  { id: 292, en: "bridge", es: "puente", nl: "brug", type: "noun", g: "m", ex: { es: "Cruza el puente.", nl: "Steek de brug over." } },
  { id: 293, en: "building", es: "edificio", nl: "gebouw", type: "noun", g: "m", ex: { es: "El edificio es muy alto.", nl: "Het gebouw is heel hoog." } },
  { id: 294, en: "floor", es: "suelo / piso", nl: "vloer / verdieping", type: "noun", g: "m", ex: { es: "El suelo está mojado.", nl: "De vloer is nat." } },
  { id: 295, en: "wall", es: "pared / muro", nl: "muur / wand", type: "noun", g: "f", ex: { es: "Hay un cuadro en la pared.", nl: "Er hangt een schilderij aan de muur." } },
  { id: 296, en: "roof", es: "techo / tejado", nl: "dak", type: "noun", g: "m", ex: { es: "El techo necesita reparación.", nl: "Het dak moet gerepareerd worden." } },
  { id: 297, en: "story, history", es: "historia", nl: "verhaal / geschiedenis", type: "noun", g: "f", ex: { es: "Cuéntame una historia.", nl: "Vertel me een verhaal." } },
  { id: 298, en: "truth", es: "verdad", nl: "waarheid", type: "noun", g: "f", ex: { es: "Dime la verdad.", nl: "Vertel me de waarheid." } },
  { id: 299, en: "mistake, error", es: "error / equivocación", nl: "fout / vergissing", type: "noun", g: "m", ex: { es: "Cometí un error.", nl: "Ik heb een fout gemaakt." } },
  { id: 300, en: "part", es: "parte", nl: "deel", type: "noun", g: "f", ex: { es: "Esta es la mejor parte.", nl: "Dit is het beste deel." } },
  { id: 301, en: "dream", es: "sueño", nl: "droom", type: "noun", g: "m", ex: { es: "Tuve un sueño extraño.", nl: "Ik had een vreemde droom." } },
  { id: 302, en: "peace", es: "paz", nl: "vrede", type: "noun", g: "f", ex: { es: "Queremos paz.", nl: "We willen vrede." } },
  { id: 303, en: "war", es: "guerra", nl: "oorlog", type: "noun", g: "f", ex: { es: "La guerra es terrible.", nl: "De oorlog is verschrikkelijk." } },
  { id: 304, en: "death", es: "muerte", nl: "dood", type: "noun", g: "f", ex: { es: "La muerte es parte de la vida.", nl: "De dood hoort bij het leven." } },
  { id: 305, en: "love", es: "amor", nl: "liefde", type: "noun", g: "m", ex: { es: "El amor es importante.", nl: "Liefde is belangrijk." } },
  { id: 306, en: "weather", es: "tiempo / clima", nl: "weer", type: "noun", g: "m", ex: { es: "¿Cómo está el tiempo?", nl: "Hoe is het weer?" } },
  { id: 307, en: "price", es: "precio", nl: "prijs", type: "noun", g: "m", ex: { es: "¿Cuál es el precio?", nl: "Wat is de prijs?" } },
  { id: 308, en: "news", es: "noticias", nl: "nieuws", type: "noun", g: "f", ex: { es: "¿Has visto las noticias?", nl: "Heb je het nieuws gezien?" } },
  { id: 309, en: "health", es: "salud", nl: "gezondheid", type: "noun", g: "f", ex: { es: "La salud es lo primero.", nl: "Gezondheid gaat voor." } },
  { id: 310, en: "pain", es: "dolor", nl: "pijn", type: "noun", g: "m", ex: { es: "Tengo dolor de cabeza.", nl: "Ik heb hoofdpijn." } },
  { id: 311, en: "voice", es: "voz", nl: "stem", type: "noun", g: "f", ex: { es: "Tiene una voz bonita.", nl: "Ze heeft een mooie stem." } },
  { id: 312, en: "color", es: "color", nl: "kleur", type: "noun", g: "m", ex: { es: "¿Cuál es tu color favorito?", nl: "Wat is je favoriete kleur?" } },
  { id: 313, en: "mind", es: "mente", nl: "geest / verstand", type: "noun", g: "f", ex: { es: "Tienes una mente brillante.", nl: "Je hebt een briljante geest." } },
  { id: 314, en: "side", es: "lado", nl: "kant / zijde", type: "noun", g: "m", ex: { es: "Está al otro lado.", nl: "Het is aan de andere kant." } },
  { id: 315, en: "end", es: "fin / final", nl: "einde", type: "noun", g: "m", ex: { es: "Es el fin de la historia.", nl: "Het is het einde van het verhaal." } },
  { id: 316, en: "beginning", es: "principio / comienzo", nl: "begin", type: "noun", g: "m", ex: { es: "Desde el principio.", nl: "Vanaf het begin." } },
  { id: 317, en: "right (direction)", es: "derecha", nl: "rechts", type: "noun", g: "f", ex: { es: "Gira a la derecha.", nl: "Ga naar rechts." } },
  { id: 318, en: "left (direction)", es: "izquierda", nl: "links", type: "noun", g: "f", ex: { es: "Gira a la izquierda.", nl: "Ga naar links." } },
  { id: 319, en: "top, above", es: "arriba / encima", nl: "boven", type: "adverb", ex: { es: "Está arriba.", nl: "Het is boven." } },
  { id: 320, en: "bottom, below", es: "abajo / debajo", nl: "beneden / onder", type: "adverb", ex: { es: "Está abajo.", nl: "Het is beneden." } },
  { id: 321, en: "God", es: "Dios", nl: "God", type: "noun", g: "m", ex: { es: "Dios mío.", nl: "Mijn God." } },
  { id: 322, en: "party (celebration)", es: "fiesta", nl: "feest", type: "noun", g: "f", ex: { es: "¡Vamos a la fiesta!", nl: "We gaan naar het feest!" } },
  { id: 323, en: "government", es: "gobierno", nl: "overheid / regering", type: "noun", g: "m", ex: { es: "El gobierno tomó una decisión.", nl: "De overheid heeft een besluit genomen." } },
  { id: 324, en: "power", es: "poder", nl: "macht / kracht", type: "noun", g: "m", ex: { es: "El conocimiento es poder.", nl: "Kennis is macht." } },
  { id: 325, en: "field", es: "campo", nl: "veld", type: "noun", g: "m", ex: { es: "El campo es verde.", nl: "Het veld is groen." } },
  { id: 326, en: "information", es: "información", nl: "informatie", type: "noun", g: "f", ex: { es: "Necesito más información.", nl: "Ik heb meer informatie nodig." } },
  { id: 327, en: "example", es: "ejemplo", nl: "voorbeeld", type: "noun", g: "m", ex: { es: "Dame un ejemplo.", nl: "Geef me een voorbeeld." } },
  { id: 328, en: "experience", es: "experiencia", nl: "ervaring", type: "noun", g: "f", ex: { es: "Fue una buena experiencia.", nl: "Het was een goede ervaring." } },
  { id: 329, en: "company", es: "empresa / compañía", nl: "bedrijf", type: "noun", g: "f", ex: { es: "Trabajo en una empresa grande.", nl: "Ik werk bij een groot bedrijf." } },
  { id: 330, en: "future", es: "futuro", nl: "toekomst", type: "noun", g: "m", ex: { es: "El futuro es incierto.", nl: "De toekomst is onzeker." } },
  { id: 331, en: "past", es: "pasado", nl: "verleden", type: "noun", g: "m", ex: { es: "Olvida el pasado.", nl: "Vergeet het verleden." } },
  { id: 332, en: "moment", es: "momento", nl: "moment", type: "noun", g: "m", ex: { es: "Espera un momento.", nl: "Wacht even een moment." } },
  { id: 333, en: "reason", es: "razón / motivo", nl: "reden", type: "noun", g: "f", ex: { es: "Tienes razón.", nl: "Je hebt gelijk." } },
  { id: 334, en: "law", es: "ley", nl: "wet", type: "noun", g: "f", ex: { es: "Hay que respetar la ley.", nl: "Je moet de wet respecteren." } },
  { id: 335, en: "right (legal)", es: "derecho", nl: "recht", type: "noun", g: "m", ex: { es: "Tienes derecho a saber.", nl: "Je hebt het recht om te weten." } },
  { id: 336, en: "art", es: "arte", nl: "kunst", type: "noun", g: "m", ex: { es: "Me gusta el arte moderno.", nl: "Ik hou van moderne kunst." } },
  { id: 337, en: "sport", es: "deporte", nl: "sport", type: "noun", g: "m", ex: { es: "El deporte es importante.", nl: "Sport is belangrijk." } },
  { id: 338, en: "team", es: "equipo", nl: "team / ploeg", type: "noun", g: "m", ex: { es: "Nuestro equipo ganó.", nl: "Ons team heeft gewonnen." } },
  { id: 339, en: "newspaper", es: "periódico", nl: "krant", type: "noun", g: "m", ex: { es: "Leo el periódico cada mañana.", nl: "Ik lees elke ochtend de krant." } },
  { id: 340, en: "bank", es: "banco", nl: "bank", type: "noun", g: "m", ex: { es: "Voy al banco.", nl: "Ik ga naar de bank." } },
  { id: 341, en: "corner", es: "esquina / rincón", nl: "hoek", type: "noun", g: "f", ex: { es: "Está en la esquina.", nl: "Het is op de hoek." } },
  { id: 342, en: "step", es: "paso", nl: "stap", type: "noun", g: "m", ex: { es: "Paso a paso.", nl: "Stap voor stap." } },
  { id: 343, en: "noise, sound", es: "ruido / sonido", nl: "geluid / lawaai", type: "noun", g: "m", ex: { es: "¿Qué es ese ruido?", nl: "Wat is dat geluid?" } },
  { id: 344, en: "light", es: "luz", nl: "licht", type: "noun", g: "f", ex: { es: "Enciende la luz.", nl: "Doe het licht aan." } },
  { id: 345, en: "shadow, shade", es: "sombra", nl: "schaduw", type: "noun", g: "f", ex: { es: "Descansamos a la sombra.", nl: "We rusten in de schaduw." } },
  { id: 346, en: "space", es: "espacio", nl: "ruimte", type: "noun", g: "m", ex: { es: "No hay espacio.", nl: "Er is geen ruimte." } },
  { id: 347, en: "sign", es: "señal / signo", nl: "teken / bord", type: "noun", g: "f", ex: { es: "Es una buena señal.", nl: "Het is een goed teken." } },
  { id: 348, en: "luck", es: "suerte", nl: "geluk", type: "noun", g: "f", ex: { es: "¡Buena suerte!", nl: "Veel geluk!" } },
  { id: 349, en: "memory", es: "memoria / recuerdo", nl: "herinnering / geheugen", type: "noun", g: "f", ex: { es: "Tengo mala memoria.", nl: "Ik heb een slecht geheugen." } },
  { id: 350, en: "thought", es: "pensamiento", nl: "gedachte", type: "noun", g: "m", ex: { es: "Es un buen pensamiento.", nl: "Het is een goede gedachte." } },

  // ── 351–430: Adjectives ─────────────────────────────────────────
  { id: 351, en: "good", es: "bueno / buena", nl: "goed", type: "adjective", ex: { es: "Es una buena idea.", nl: "Het is een goed idee." } },
  { id: 352, en: "bad", es: "malo / mala", nl: "slecht", type: "adjective", ex: { es: "Es un mal día.", nl: "Het is een slechte dag." } },
  { id: 353, en: "big, large", es: "grande", nl: "groot", type: "adjective", ex: { es: "La casa es grande.", nl: "Het huis is groot." } },
  { id: 354, en: "small, little", es: "pequeño", nl: "klein", type: "adjective", ex: { es: "Tengo un perro pequeño.", nl: "Ik heb een kleine hond." } },
  { id: 355, en: "new", es: "nuevo", nl: "nieuw", type: "adjective", ex: { es: "Tengo un coche nuevo.", nl: "Ik heb een nieuwe auto." } },
  { id: 356, en: "old", es: "viejo / antiguo", nl: "oud", type: "adjective", ex: { es: "La ciudad es vieja.", nl: "De stad is oud." } },
  { id: 357, en: "young", es: "joven", nl: "jong", type: "adjective", ex: { es: "Es muy joven.", nl: "Hij is heel jong." } },
  { id: 358, en: "long", es: "largo", nl: "lang", type: "adjective", ex: { es: "El viaje es largo.", nl: "De reis is lang." } },
  { id: 359, en: "short (length)", es: "corto", nl: "kort", type: "adjective", ex: { es: "La calle es corta.", nl: "De straat is kort." } },
  { id: 360, en: "tall, high", es: "alto", nl: "hoog / lang", type: "adjective", ex: { es: "El edificio es alto.", nl: "Het gebouw is hoog." } },
  { id: 361, en: "beautiful", es: "hermoso / bonito", nl: "mooi", type: "adjective", ex: { es: "El paisaje es hermoso.", nl: "Het landschap is mooi." } },
  { id: 362, en: "ugly", es: "feo", nl: "lelijk", type: "adjective", ex: { es: "El cuadro es feo.", nl: "Het schilderij is lelijk." } },
  { id: 363, en: "happy", es: "feliz / contento", nl: "gelukkig / blij", type: "adjective", ex: { es: "Estoy muy feliz.", nl: "Ik ben erg gelukkig." } },
  { id: 364, en: "sad", es: "triste", nl: "verdrietig", type: "adjective", ex: { es: "Estoy triste hoy.", nl: "Ik ben vandaag verdrietig." } },
  { id: 365, en: "angry", es: "enfadado / enojado", nl: "boos", type: "adjective", ex: { es: "Está enfadado conmigo.", nl: "Hij is boos op mij." } },
  { id: 366, en: "afraid, scared", es: "asustado / temeroso", nl: "bang", type: "adjective", ex: { es: "Estoy asustado.", nl: "Ik ben bang." } },
  { id: 367, en: "tired", es: "cansado", nl: "moe", type: "adjective", ex: { es: "Estoy muy cansado.", nl: "Ik ben erg moe." } },
  { id: 368, en: "hungry", es: "hambriento", nl: "hongerig", type: "adjective", ex: { es: "Estoy hambriento.", nl: "Ik heb honger." } },
  { id: 369, en: "thirsty", es: "sediento", nl: "dorstig", type: "adjective", ex: { es: "Estoy sediento.", nl: "Ik heb dorst." } },
  { id: 370, en: "sick, ill", es: "enfermo", nl: "ziek", type: "adjective", ex: { es: "Estoy enfermo.", nl: "Ik ben ziek." } },
  { id: 371, en: "hot (temperature)", es: "caliente", nl: "heet / warm", type: "adjective", ex: { es: "El café está caliente.", nl: "De koffie is heet." } },
  { id: 372, en: "cold", es: "frío", nl: "koud", type: "adjective", ex: { es: "El agua está fría.", nl: "Het water is koud." } },
  { id: 373, en: "fast, quick", es: "rápido", nl: "snel", type: "adjective", ex: { es: "El tren es rápido.", nl: "De trein is snel." } },
  { id: 374, en: "slow", es: "lento", nl: "langzaam / traag", type: "adjective", ex: { es: "El autobús es lento.", nl: "De bus is langzaam." } },
  { id: 375, en: "easy", es: "fácil", nl: "makkelijk / gemakkelijk", type: "adjective", ex: { es: "Este ejercicio es fácil.", nl: "Deze oefening is makkelijk." } },
  { id: 376, en: "difficult, hard", es: "difícil", nl: "moeilijk", type: "adjective", ex: { es: "El examen es difícil.", nl: "Het examen is moeilijk." } },
  { id: 377, en: "important", es: "importante", nl: "belangrijk", type: "adjective", ex: { es: "Es muy importante.", nl: "Het is erg belangrijk." } },
  { id: 378, en: "possible", es: "posible", nl: "mogelijk", type: "adjective", ex: { es: "Todo es posible.", nl: "Alles is mogelijk." } },
  { id: 379, en: "necessary", es: "necesario", nl: "noodzakelijk / nodig", type: "adjective", ex: { es: "Es necesario hacerlo.", nl: "Het is nodig om het te doen." } },
  { id: 380, en: "free", es: "libre / gratis", nl: "vrij / gratis", type: "adjective", ex: { es: "La entrada es gratis.", nl: "De toegang is gratis." } },
  { id: 381, en: "strong", es: "fuerte", nl: "sterk", type: "adjective", ex: { es: "El tiene brazos fuertes.", nl: "Hij heeft sterke armen." } },
  { id: 382, en: "weak", es: "débil", nl: "zwak", type: "adjective", ex: { es: "Me siento débil.", nl: "Ik voel me zwak." } },
  { id: 383, en: "heavy", es: "pesado", nl: "zwaar", type: "adjective", ex: { es: "La maleta es pesada.", nl: "De koffer is zwaar." } },
  { id: 384, en: "light (weight)", es: "ligero / liviano", nl: "licht", type: "adjective", ex: { es: "La bolsa es ligera.", nl: "De tas is licht." } },
  { id: 385, en: "clean", es: "limpio", nl: "schoon", type: "adjective", ex: { es: "La cocina está limpia.", nl: "De keuken is schoon." } },
  { id: 386, en: "dirty", es: "sucio", nl: "vies / vuil", type: "adjective", ex: { es: "Los zapatos están sucios.", nl: "De schoenen zijn vies." } },
  { id: 387, en: "empty", es: "vacío", nl: "leeg", type: "adjective", ex: { es: "La botella está vacía.", nl: "De fles is leeg." } },
  { id: 388, en: "full", es: "lleno", nl: "vol", type: "adjective", ex: { es: "El vaso está lleno.", nl: "Het glas is vol." } },
  { id: 389, en: "rich", es: "rico", nl: "rijk", type: "adjective", ex: { es: "Es un hombre rico.", nl: "Hij is een rijke man." } },
  { id: 390, en: "poor", es: "pobre", nl: "arm", type: "adjective", ex: { es: "Es un barrio pobre.", nl: "Het is een arme wijk." } },
  { id: 391, en: "open", es: "abierto", nl: "open", type: "adjective", ex: { es: "La tienda está abierta.", nl: "De winkel is open." } },
  { id: 392, en: "closed", es: "cerrado", nl: "gesloten / dicht", type: "adjective", ex: { es: "La puerta está cerrada.", nl: "De deur is dicht." } },
  { id: 393, en: "dark", es: "oscuro", nl: "donker", type: "adjective", ex: { es: "La habitación está oscura.", nl: "De kamer is donker." } },
  { id: 394, en: "bright", es: "brillante / claro", nl: "helder / licht", type: "adjective", ex: { es: "El sol es brillante.", nl: "De zon is helder." } },
  { id: 395, en: "dry", es: "seco", nl: "droog", type: "adjective", ex: { es: "El clima es seco.", nl: "Het klimaat is droog." } },
  { id: 396, en: "wet", es: "mojado / húmedo", nl: "nat / vochtig", type: "adjective", ex: { es: "El suelo está mojado.", nl: "De vloer is nat." } },
  { id: 397, en: "soft", es: "suave / blando", nl: "zacht", type: "adjective", ex: { es: "La almohada es suave.", nl: "Het kussen is zacht." } },
  { id: 398, en: "hard (texture)", es: "duro", nl: "hard", type: "adjective", ex: { es: "La cama es dura.", nl: "Het bed is hard." } },
  { id: 399, en: "wide", es: "ancho / amplio", nl: "breed / wijd", type: "adjective", ex: { es: "La calle es ancha.", nl: "De straat is breed." } },
  { id: 400, en: "narrow", es: "estrecho", nl: "smal / nauw", type: "adjective", ex: { es: "El camino es estrecho.", nl: "De weg is smal." } },
  { id: 401, en: "deep", es: "profundo", nl: "diep", type: "adjective", ex: { es: "El río es profundo.", nl: "De rivier is diep." } },
  { id: 402, en: "flat", es: "plano", nl: "plat / vlak", type: "adjective", ex: { es: "Los Países Bajos son planos.", nl: "Nederland is plat." } },
  { id: 403, en: "round", es: "redondo", nl: "rond", type: "adjective", ex: { es: "La tierra es redonda.", nl: "De aarde is rond." } },
  { id: 404, en: "straight", es: "recto / derecho", nl: "recht", type: "adjective", ex: { es: "Sigue todo recto.", nl: "Ga rechtdoor." } },
  { id: 405, en: "safe", es: "seguro", nl: "veilig", type: "adjective", ex: { es: "Este barrio es seguro.", nl: "Deze buurt is veilig." } },
  { id: 406, en: "dangerous", es: "peligroso", nl: "gevaarlijk", type: "adjective", ex: { es: "Es un camino peligroso.", nl: "Het is een gevaarlijke weg." } },
  { id: 407, en: "correct, right", es: "correcto", nl: "juist / correct", type: "adjective", ex: { es: "La respuesta es correcta.", nl: "Het antwoord is juist." } },
  { id: 408, en: "wrong", es: "equivocado / incorrecto", nl: "fout / verkeerd", type: "adjective", ex: { es: "Estás equivocado.", nl: "Je hebt het fout." } },
  { id: 409, en: "different", es: "diferente / distinto", nl: "anders / verschillend", type: "adjective", ex: { es: "Cada persona es diferente.", nl: "Iedereen is anders." } },
  { id: 410, en: "same", es: "mismo / igual", nl: "hetzelfde / gelijk", type: "adjective", ex: { es: "Tenemos el mismo profesor.", nl: "We hebben dezelfde leraar." } },
  { id: 411, en: "alone", es: "solo", nl: "alleen", type: "adjective", ex: { es: "Vivo solo.", nl: "Ik woon alleen." } },
  { id: 412, en: "together", es: "juntos", nl: "samen", type: "adverb", ex: { es: "Trabajamos juntos.", nl: "We werken samen." } },
  { id: 413, en: "ready", es: "listo / preparado", nl: "klaar", type: "adjective", ex: { es: "¿Estás listo?", nl: "Ben je klaar?" } },
  { id: 414, en: "busy", es: "ocupado", nl: "druk / bezig", type: "adjective", ex: { es: "Estoy muy ocupado.", nl: "Ik ben erg druk." } },
  { id: 415, en: "quiet", es: "tranquilo / silencioso", nl: "stil / rustig", type: "adjective", ex: { es: "La noche es tranquila.", nl: "De nacht is stil." } },
  { id: 416, en: "loud", es: "ruidoso / fuerte", nl: "luid / hard", type: "adjective", ex: { es: "La música es muy fuerte.", nl: "De muziek is erg luid." } },
  { id: 417, en: "sweet", es: "dulce", nl: "zoet / lief", type: "adjective", ex: { es: "El pastel es dulce.", nl: "De taart is zoet." } },
  { id: 418, en: "bitter", es: "amargo", nl: "bitter", type: "adjective", ex: { es: "El café es amargo.", nl: "De koffie is bitter." } },
  { id: 419, en: "delicious, tasty", es: "delicioso / rico", nl: "lekker / heerlijk", type: "adjective", ex: { es: "La comida está deliciosa.", nl: "Het eten is heerlijk." } },
  { id: 420, en: "funny", es: "gracioso / divertido", nl: "grappig / leuk", type: "adjective", ex: { es: "La película es divertida.", nl: "De film is grappig." } },
  { id: 421, en: "interesting", es: "interesante", nl: "interessant", type: "adjective", ex: { es: "El libro es interesante.", nl: "Het boek is interessant." } },
  { id: 422, en: "boring", es: "aburrido", nl: "saai / vervelend", type: "adjective", ex: { es: "La clase es aburrida.", nl: "De les is saai." } },
  { id: 423, en: "popular", es: "popular", nl: "populair", type: "adjective", ex: { es: "Es un restaurante popular.", nl: "Het is een populair restaurant." } },
  { id: 424, en: "famous", es: "famoso", nl: "beroemd", type: "adjective", ex: { es: "Es un actor famoso.", nl: "Hij is een beroemde acteur." } },
  { id: 425, en: "strange, weird", es: "extraño / raro", nl: "vreemd / raar", type: "adjective", ex: { es: "Qué situación tan extraña.", nl: "Wat een vreemde situatie." } },
  { id: 426, en: "normal", es: "normal", nl: "normaal", type: "adjective", ex: { es: "Es completamente normal.", nl: "Het is helemaal normaal." } },
  { id: 427, en: "perfect", es: "perfecto", nl: "perfect", type: "adjective", ex: { es: "Es un día perfecto.", nl: "Het is een perfecte dag." } },
  { id: 428, en: "special", es: "especial", nl: "speciaal / bijzonder", type: "adjective", ex: { es: "Eres muy especial.", nl: "Je bent heel bijzonder." } },
  { id: 429, en: "real, true", es: "real / verdadero", nl: "echt / waar", type: "adjective", ex: { es: "¿Es real?", nl: "Is het echt?" } },
  { id: 430, en: "simple", es: "simple / sencillo", nl: "eenvoudig / simpel", type: "adjective", ex: { es: "La solución es simple.", nl: "De oplossing is eenvoudig." } },

  // ── 431–465: Adverbs & More ─────────────────────────────────────
  { id: 431, en: "quickly", es: "rápidamente", nl: "snel", type: "adverb", ex: { es: "Camina rápidamente.", nl: "Loop snel." } },
  { id: 432, en: "slowly", es: "lentamente / despacio", nl: "langzaam", type: "adverb", ex: { es: "Habla despacio, por favor.", nl: "Spreek langzaam, alsjeblieft." } },
  { id: 433, en: "only, just", es: "solo / solamente", nl: "alleen / slechts", type: "adverb", ex: { es: "Solo quiero dormir.", nl: "Ik wil alleen maar slapen." } },
  { id: 434, en: "perhaps, maybe", es: "quizás / tal vez", nl: "misschien", type: "adverb", ex: { es: "Quizás llueva mañana.", nl: "Misschien regent het morgen." } },
  { id: 435, en: "often", es: "a menudo / frecuentemente", nl: "vaak", type: "adverb", ex: { es: "Voy a menudo al cine.", nl: "Ik ga vaak naar de bioscoop." } },
  { id: 436, en: "sometimes", es: "a veces", nl: "soms", type: "adverb", ex: { es: "A veces llueve.", nl: "Soms regent het." } },
  { id: 437, en: "usually", es: "normalmente / generalmente", nl: "meestal / gewoonlijk", type: "adverb", ex: { es: "Normalmente como a las dos.", nl: "Meestal eet ik om twee uur." } },
  { id: 438, en: "almost", es: "casi", nl: "bijna", type: "adverb", ex: { es: "Casi estamos listos.", nl: "We zijn bijna klaar." } },
  { id: 439, en: "enough", es: "bastante / suficiente", nl: "genoeg", type: "adverb", ex: { es: "Tengo bastante dinero.", nl: "Ik heb genoeg geld." } },
  { id: 440, en: "soon", es: "pronto", nl: "binnenkort / gauw", type: "adverb", ex: { es: "Volveremos pronto.", nl: "We komen binnenkort terug." } },
  { id: 441, en: "late", es: "tarde", nl: "laat", type: "adverb", ex: { es: "Llegamos tarde.", nl: "We komen te laat." } },
  { id: 442, en: "early", es: "temprano", nl: "vroeg", type: "adverb", ex: { es: "Me levanto temprano.", nl: "Ik sta vroeg op." } },
  { id: 443, en: "recently", es: "recientemente", nl: "onlangs / recent", type: "adverb", ex: { es: "Recientemente visité España.", nl: "Ik heb onlangs Spanje bezocht." } },
  { id: 444, en: "again", es: "otra vez / de nuevo", nl: "weer / opnieuw", type: "adverb", ex: { es: "Inténtalo otra vez.", nl: "Probeer het opnieuw." } },
  { id: 445, en: "still, yet", es: "todavía / aún", nl: "nog / nog steeds", type: "adverb", ex: { es: "Todavía está lloviendo.", nl: "Het regent nog steeds." } },
  { id: 446, en: "so, therefore", es: "así que / entonces", nl: "dus / daarom", type: "conjunction", ex: { es: "Así que viniste.", nl: "Dus je bent gekomen." } },
  { id: 447, en: "however, though", es: "sin embargo", nl: "echter / toch", type: "conjunction", ex: { es: "Sin embargo, no fue fácil.", nl: "Het was echter niet makkelijk." } },
  { id: 448, en: "if", es: "si", nl: "als", type: "conjunction", ex: { es: "Si llueve, me quedo en casa.", nl: "Als het regent, blijf ik thuis." } },
  { id: 449, en: "than", es: "que (comparative)", nl: "dan", type: "conjunction", ex: { es: "Es más alto que yo.", nl: "Hij is langer dan ik." } },
  { id: 450, en: "while", es: "mientras", nl: "terwijl", type: "conjunction", ex: { es: "Lee mientras esperas.", nl: "Lees terwijl je wacht." } },
  { id: 451, en: "although", es: "aunque", nl: "hoewel / alhoewel", type: "conjunction", ex: { es: "Aunque es difícil, lo intento.", nl: "Hoewel het moeilijk is, probeer ik het." } },
  { id: 452, en: "everything", es: "todo", nl: "alles", type: "pronoun", ex: { es: "Todo está bien.", nl: "Alles is goed." } },
  { id: 453, en: "nothing", es: "nada", nl: "niets", type: "pronoun", ex: { es: "No quiero nada.", nl: "Ik wil niets." } },
  { id: 454, en: "something", es: "algo", nl: "iets", type: "pronoun", ex: { es: "¿Quieres algo?", nl: "Wil je iets?" } },
  { id: 455, en: "everyone", es: "todos / todo el mundo", nl: "iedereen", type: "pronoun", ex: { es: "Todos están invitados.", nl: "Iedereen is uitgenodigd." } },
  { id: 456, en: "nobody, no one", es: "nadie", nl: "niemand", type: "pronoun", ex: { es: "No hay nadie aquí.", nl: "Er is niemand hier." } },
  { id: 457, en: "someone", es: "alguien", nl: "iemand", type: "pronoun", ex: { es: "¿Hay alguien ahí?", nl: "Is daar iemand?" } },
  { id: 458, en: "each, every", es: "cada", nl: "elke / iedere", type: "adjective", ex: { es: "Cada día es nuevo.", nl: "Elke dag is nieuw." } },
  { id: 459, en: "own", es: "propio", nl: "eigen", type: "adjective", ex: { es: "Tengo mi propio coche.", nl: "Ik heb mijn eigen auto." } },
  { id: 460, en: "several", es: "varios", nl: "verschillende / meerdere", type: "adjective", ex: { es: "Tengo varios libros.", nl: "Ik heb meerdere boeken." } },
  { id: 461, en: "whole, entire", es: "entero", nl: "heel / geheel", type: "adjective", ex: { es: "Recorrió el país entero.", nl: "Hij reisde het hele land door." } },
  { id: 462, en: "last (final)", es: "último", nl: "laatste", type: "adjective", ex: { es: "Es el último día.", nl: "Het is de laatste dag." } },
  { id: 463, en: "next", es: "próximo / siguiente", nl: "volgende", type: "adjective", ex: { es: "La próxima vez.", nl: "De volgende keer." } },
  { id: 464, en: "first", es: "primero", nl: "eerste", type: "adjective", ex: { es: "Es la primera vez.", nl: "Het is de eerste keer." } },
  { id: 465, en: "second", es: "segundo", nl: "tweede", type: "adjective", ex: { es: "Espera un segundo.", nl: "Wacht een seconde." } },

  // ── 466–500: Numbers, Colors, Days, Useful Phrases ──────────────
  { id: 466, en: "zero", es: "cero", nl: "nul", type: "number", ex: { es: "El resultado es cero.", nl: "Het resultaat is nul." } },
  { id: 467, en: "one", es: "uno", nl: "een", type: "number", ex: { es: "Solo quiero uno.", nl: "Ik wil er maar een." } },
  { id: 468, en: "two", es: "dos", nl: "twee", type: "number", ex: { es: "Tengo dos hermanos.", nl: "Ik heb twee broers." } },
  { id: 469, en: "three", es: "tres", nl: "drie", type: "number", ex: { es: "Tres es mi número favorito.", nl: "Drie is mijn favoriete nummer." } },
  { id: 470, en: "four", es: "cuatro", nl: "vier", type: "number", ex: { es: "Hay cuatro estaciones.", nl: "Er zijn vier seizoenen." } },
  { id: 471, en: "five", es: "cinco", nl: "vijf", type: "number", ex: { es: "Tengo cinco dedos.", nl: "Ik heb vijf vingers." } },
  { id: 472, en: "ten", es: "diez", nl: "tien", type: "number", ex: { es: "Diez más diez son veinte.", nl: "Tien plus tien is twintig." } },
  { id: 473, en: "hundred", es: "cien / ciento", nl: "honderd", type: "number", ex: { es: "Cuesta cien euros.", nl: "Het kost honderd euro." } },
  { id: 474, en: "thousand", es: "mil", nl: "duizend", type: "number", ex: { es: "Hay mil razones.", nl: "Er zijn duizend redenen." } },
  { id: 475, en: "red", es: "rojo", nl: "rood", type: "adjective", ex: { es: "Mi coche es rojo.", nl: "Mijn auto is rood." } },
  { id: 476, en: "blue", es: "azul", nl: "blauw", type: "adjective", ex: { es: "El cielo es azul.", nl: "De lucht is blauw." } },
  { id: 477, en: "green", es: "verde", nl: "groen", type: "adjective", ex: { es: "La hierba es verde.", nl: "Het gras is groen." } },
  { id: 478, en: "yellow", es: "amarillo", nl: "geel", type: "adjective", ex: { es: "El sol es amarillo.", nl: "De zon is geel." } },
  { id: 479, en: "white", es: "blanco", nl: "wit", type: "adjective", ex: { es: "La nieve es blanca.", nl: "De sneeuw is wit." } },
  { id: 480, en: "black", es: "negro", nl: "zwart", type: "adjective", ex: { es: "Llevo zapatos negros.", nl: "Ik draag zwarte schoenen." } },
  { id: 481, en: "Monday", es: "lunes", nl: "maandag", type: "noun", g: "m", ex: { es: "El lunes trabajo.", nl: "Op maandag werk ik." } },
  { id: 482, en: "Tuesday", es: "martes", nl: "dinsdag", type: "noun", g: "m", ex: { es: "El martes tengo clase.", nl: "Op dinsdag heb ik les." } },
  { id: 483, en: "Wednesday", es: "miércoles", nl: "woensdag", type: "noun", g: "m", ex: { es: "El miércoles es festivo.", nl: "Woensdag is een feestdag." } },
  { id: 484, en: "Thursday", es: "jueves", nl: "donderdag", type: "noun", g: "m", ex: { es: "El jueves voy al cine.", nl: "Donderdag ga ik naar de bioscoop." } },
  { id: 485, en: "Friday", es: "viernes", nl: "vrijdag", type: "noun", g: "m", ex: { es: "¡Por fin es viernes!", nl: "Eindelijk vrijdag!" } },
  { id: 486, en: "Saturday", es: "sábado", nl: "zaterdag", type: "noun", g: "m", ex: { es: "El sábado vamos de compras.", nl: "Zaterdag gaan we winkelen." } },
  { id: 487, en: "Sunday", es: "domingo", nl: "zondag", type: "noun", g: "m", ex: { es: "El domingo descanso.", nl: "Zondag rust ik uit." } },
  { id: 488, en: "please", es: "por favor", nl: "alsjeblieft / alstublieft", type: "phrase", ex: { es: "Un café, por favor.", nl: "Een koffie, alsjeblieft." } },
  { id: 489, en: "thank you", es: "gracias", nl: "dank je / bedankt", type: "phrase", ex: { es: "Muchas gracias.", nl: "Heel erg bedankt." } },
  { id: 490, en: "sorry, excuse me", es: "perdón / disculpa", nl: "sorry / pardon", type: "phrase", ex: { es: "Perdón, no fue mi intención.", nl: "Sorry, het was niet mijn bedoeling." } },
  { id: 491, en: "hello", es: "hola", nl: "hallo", type: "phrase", ex: { es: "¡Hola! ¿Cómo estás?", nl: "Hallo! Hoe gaat het?" } },
  { id: 492, en: "goodbye", es: "adiós", nl: "dag / tot ziens", type: "phrase", ex: { es: "Adiós, hasta luego.", nl: "Dag, tot ziens." } },
  { id: 493, en: "good morning", es: "buenos días", nl: "goedemorgen", type: "phrase", ex: { es: "Buenos días, señor.", nl: "Goedemorgen, meneer." } },
  { id: 494, en: "good night", es: "buenas noches", nl: "goedenacht", type: "phrase", ex: { es: "Buenas noches, dulces sueños.", nl: "Goedenacht, slaap lekker." } },
  { id: 495, en: "congratulations", es: "felicidades / enhorabuena", nl: "gefeliciteerd", type: "phrase", ex: { es: "¡Felicidades por tu cumpleaños!", nl: "Gefeliciteerd met je verjaardag!" } },
  { id: 496, en: "welcome", es: "bienvenido", nl: "welkom", type: "phrase", ex: { es: "¡Bienvenido a España!", nl: "Welkom in Nederland!" } },
  { id: 497, en: "of course", es: "por supuesto / claro", nl: "natuurlijk", type: "phrase", ex: { es: "¡Por supuesto que sí!", nl: "Natuurlijk!" } },
  { id: 498, en: "I don't understand", es: "no entiendo", nl: "ik begrijp het niet", type: "phrase", ex: { es: "Lo siento, no entiendo.", nl: "Sorry, ik begrijp het niet." } },
  { id: 499, en: "how much / how many", es: "cuánto / cuántos", nl: "hoeveel", type: "phrase", ex: { es: "¿Cuánto cuesta?", nl: "Hoeveel kost het?" } },
  { id: 500, en: "I would like", es: "me gustaría / quisiera", nl: "ik zou graag willen", type: "phrase", ex: { es: "Me gustaría reservar una mesa.", nl: "Ik zou graag een tafel willen reserveren." } },
];

// Language metadata for the app
const LANGUAGES = {
  en: { name: "English", flag: "🇬🇧", code: "en", ttsLang: "en-GB" },
  es: { name: "Spanish", flag: "🇪🇸", code: "es", ttsLang: "es-ES" },
  nl: { name: "Dutch",   flag: "🇳🇱", code: "nl", ttsLang: "nl-NL" },
};

const LANG_KEYS = ["en", "es", "nl"];
